databankadmin@databank:/opt/RDFDatabank/rdfdatabank/tests/RDFDatabank$ python TestSubmission.py testDeleteEmbargo
/opt/RDFDatabank/rdfdatabank/tests/RDFDatabank/rdflib/plugin.py:94: UserWarning: Module rdflib was already imported from /opt/RDFDatabank/rdfdatabank/tests/RDFDatabank/rdflib/__init__.pyc, but /usr/local/lib/python2.6/dist-packages/rdflib-2.4.2-py2.6-linux-i686.egg is being added to sys.path
  from pkg_resources import iter_entry_points
Delete embargo information - POST embargo_change to /silo_name/datasets/dataset_name ... DEBUG:SparqlQueryTestCase:setRequestEndPoint: endpointhost databank.ora.ox.ac.uk:
DEBUG:SparqlQueryTestCase:setRequestEndPoint: endpointpath /sandbox/:
DEBUG:SparqlQueryTestCase:setRequestEndPoint: endpointuser admin:
DEBUG:SparqlQueryTestCase:setRequestEndPoint: endpointpass test:
DEBUG:SparqlQueryTestCase:DELETE http://databank.ora.ox.ac.uk/sandbox/datasets/TestSubmission
DEBUG:SparqlQueryTestCase:Status: 404 Not Found
DEBUG:SparqlQueryTestCase:POST http://databank.ora.ox.ac.uk/sandbox/datasets/
DEBUG:SparqlQueryTestCase:Status: 201 Created
DEBUG:SparqlQueryTestCase:GET http://databank.ora.ox.ac.uk/sandbox/datasets/TestSubmission
DEBUG:SparqlQueryTestCase:Status: 200 OK
DEBUG:SparqlQueryTestCase:POST http://databank.ora.ox.ac.uk/sandbox/datasets/TestSubmission
DEBUG:SparqlQueryTestCase:Status: 204 Updated
DEBUG:SparqlQueryTestCase:GET http://databank.ora.ox.ac.uk/sandbox/datasets/TestSubmission
DEBUG:SparqlQueryTestCase:Status: 200 OK
DEBUG:SparqlQueryTestCase:GET http://databank.ora.ox.ac.uk/sandbox/states/TestSubmission
DEBUG:SparqlQueryTestCase:Status: 200 OK
ERROR

======================================================================
ERROR: Delete embargo information - POST embargo_change to /silo_name/datasets/dataset_name
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestSubmission.py", line 1394, in testDeleteEmbargo
    expect_status=200, expect_reason="OK", expect_type="application/json")
  File "../TestLib/SparqlQueryTestCase.py", line 182, in doHTTP_GET
    if (expect_type.lower() == "application/json"): responsedata = simplejson.loads(responsedata)
  File "/usr/lib/pymodules/python2.6/simplejson/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/pymodules/python2.6/simplejson/decoder.py", line 338, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 4 - line 11 column 1372 (char 4 - 1664)

----------------------------------------------------------------------
Ran 1 test in 19.271s

FAILED (errors=1)
